_BASE_: maskformer2_R50_bs16_160k.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
    USE_CHECKPOINT: True
  WEIGHTS: "/home/jaehyunkang/MaskDINO_dacon/output/dacon/dino_slice_base256_rotation/model_0047999.pth"
  PIXEL_MEAN: [87.3359904, 91.29594915, 83.01340125]
  PIXEL_STD: [43.7584692, 38.600545950000004, 35.4384822]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 200
    FREEZE_BACKBONE: True
DATASETS:
  TRAIN: ("dacon_sem_seg_train_slice",)
  TEST: ("dacon_sem_seg_val_slice",)
SOLVER:
  IMS_PER_BATCH: 64
  BASE_LR: 0.0001
  STEPS: (40000, 45000)
  MAX_ITER: 50000
  LR_SCHEDULER_NAME: WarmupPolyLR
  POLY_LR_CONSTANT_ENDING: 0.00001
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 1000
INPUT:
  MIN_SIZE_TRAIN: (256,)
  MAX_SIZE_TRAIN: 256
  MAX_SIZE_TEST: 256
  MIN_SIZE_TEST: 256
  COLOR_AUG_SSD: false
  AUG_VER: 1
  DATASET_MAPPER_NAME: "mask_former_semantic"
OUTPUT_DIR: "output/dacon/mfs_slice_base256_freezefromdino"
