_BASE_: ../maskformer2_R50_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: "checkpoints/swin_large_patch4_window12_384_22k.pkl"
  PIXEL_MEAN: [87.3359904, 91.29594915, 83.01340125]
  PIXEL_STD: [43.7584692, 38.600545950000004, 35.4384822]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 200
SOLVER:
  STEPS: (655556, 710184)
  MAX_ITER: 737500
